### ISSUE TITLE
curl_init() 方法找不到

### ISSUE THREAD

**Issue by haoqing-yan** [Jacklucn/reserveIphone12Pro#1]
- php7.4 环境直接运行
运行以下命令 php reserveIphone12Pro.php
有这个错误
Uncaught Error: Call to undefined function curl_init()

**Comment by Jacklucn** [comment]
> * php7.4环境直接
>   运行以下命令php reserveIphone12Pro.php
>   有这个错误
>   未捕获的错误：调用未定义函数curl_init（）

**Comment by Jacklucn** [comment]
You should install the corresponding php curl extension.
你需要安装对应的 php curl 扩展。

**Comment by LuStormstout** [comment]
> * php7.4 环境直接运行
>   运行以下命令 php reserveIphone12Pro.php
>   有这个错误
>   Uncaught Error: Call to undefined function curl_init()

You should install the corresponding php curl extension.
你需要安装对应的 php curl 扩展。
